services:
  - type: web
    name: lumina-studio-mainl
    runtime: static
    rootDir: lumina-studio-main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
